# fly.toml file generated for niss-db7 on 2021-12-18T10:00:53Z

app = "niss-db7"

kill_signal = "SIGTERM"
kill_timeout = 300
processes = []
services = []

[build]
  image = "flyio/postgres:14"

[checks]

  [checks.pg]
    grace_period = "30s"
    headers = []
    interval = "15s"
    method = "get"
    path = "/flycheck/pg"
    port = 5500
    protocol = "http"
    restart_limit = 0
    timeout = "10s"
    tls_skip_verify = false
    type = "http"

  [checks.role]
    grace_period = "30s"
    headers = []
    interval = "15s"
    method = "get"
    path = "/flycheck/role"
    port = 5500
    protocol = "http"
    restart_limit = 0
    timeout = "10s"
    tls_skip_verify = false
    type = "http"

  [checks.vm]
    grace_period = "1s"
    headers = []
    interval = "1m"
    method = "get"
    path = "/flycheck/vm"
    port = 5500
    protocol = "http"
    restart_limit = 0
    timeout = "10s"
    tls_skip_verify = false
    type = "http"

[env]
  PRIMARY_REGION = "dfw"

[experimental]
  allowed_public_ports = []
  auto_rollback = false
  enable_consul = true
  private_network = true

[metrics]
  path = "/metrics"
  port = 9187

[[mounts]]
  destination = "/data"
  encrypted = false
  source = "pg_data"
